### ISSUE TITLE
Instrumentation tests coverage

### ISSUE THREAD

**Issue by elevenetc** [rafaeltoledo/unified-code-coverage-android#1]
Noticed that coverage only works for Robolectric unit test, but not for instrumentation `MainActivityTest` with `ActivityTestRule`. So if I remove `MainActivityUnitTest` coverages goes to 0%, but `MainActivityTest` is still running. Is it limitation of jacoco/report or I miss something?

**Comment by rafaeltoledo** [comment]
I runned the task here and seems to be working. Do you have some output from Gradle? Check if the task is not skipping for some reason.

**Comment by elevenetc** [comment]
Yeah, you're right. It seems I found the problem and it's about java versions which leads to wrong report generation: http://stackoverflow.com/questions/33517805/jacoco-for-report-generation-the-same-class-files-must-be-used-as-at-runtime
