### ISSUE TITLE
Cannot set the value of read-only property 'sourceDirectories' for task ':app:jacocoTestReport' 

### ISSUE THREAD

**Issue by devendroid** [rafaeltoledo/unified-code-coverage-android#12]
When adding task in build.gradle and syncing, Im getting below error:
```
A problem occurred evaluating project ':app'.
> Cannot set the value of read-only property 'sourceDirectories' for task ':app:jacocoTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.
```
What im doing wrong ?

**Comment by DamienDennehy** [comment]
For anyone who comes across this from a google, change
`    sourceDirectories = files([mainSrc])`
to
`    sourceDirectories.from = files([mainSrc])`

Do the same for the rest of the *Directories lines.

**Comment by rafaeltoledo** [comment]
I definitely need to update this repo...

**Comment by devendroid** [comment]
thanks @DamienDennehy

**Comment by rafaeltoledo** [comment]
Updated the Java and Kotlin branches to latest stable tools
