### ISSUE TITLE
Report says 0% test coverage

### ISSUE THREAD

**Issue by timmutton** [rafaeltoledo/unified-code-coverage-android#4]
Ive cloned the repo and run `./gradlew clean jacocoTestReport` and the resulting `app/build/reports/coverage/debug/net.rafaeltoledo.coverage/index.html` report says 0% test coverage

**Comment by rafaeltoledo** [comment]
The unified report path will be `/app/build/reports/jacoco/jacocoTestReport/html/index.html`. The report from the `coverage` folder is the result of the execution of the instrumented tests only. Running it on any emulator and my personal device (a first gen Pixel), shows the coverage right.

Historically, I found some devices (mostly of them, from Samsung) where the Jacoco instrumentation doesn't work, and as consequence, there's no coverage data from executions on such devices.

**Comment by timmutton** [comment]
ah, correct on both accounts. I was looking in the wrong place, and using a samsung device
